import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = path.join(root, "dist");
const tscJs = path.join(root, "node_modules", "typescript", "bin", "tsc");

fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

// Generate svg-map.ts with inlined SVG strings
const svgDir = path.join(root, "src", "svg");
const svgFiles = fs.readdirSync(svgDir).filter(f => f.endsWith(".svg")).sort();

let svgMapContent = `// Auto-generated by build.mjs — do not edit
import type { IconName } from "./registry.js";

export const svgMap: Record<IconName, string> = {
`;

for (const file of svgFiles) {
  const name = file.replace(".svg", "");
  const content = fs.readFileSync(path.join(svgDir, file), "utf8").trim();
  // Escape backticks and template literal expressions
  const escaped = content.replace(/`/g, "\\`").replace(/\$/g, "\\$");
  svgMapContent += `  ${name}: \`${escaped}\`,\n`;
}

svgMapContent += "};\n";

fs.writeFileSync(path.join(root, "src", "svg-map.ts"), svgMapContent, "utf8");

// Build TypeScript
execFileSync(
  process.execPath,
  [
    tscJs,
    "-p",
    "tsconfig.json",
    "--outDir",
    "dist/esm",
    "--declarationDir",
    "dist/types",
  ],
  {
    cwd: root,
    stdio: "inherit",
  },
);

// Copy .d.ts files to dist root
for (const file of fs.readdirSync(path.join(dist, "types"))) {
  if (file.endsWith(".d.ts")) {
    fs.copyFileSync(
      path.join(dist, "types", file),
      path.join(dist, file)
    );
  }
}

// Write ESM and CJS entry points
fs.writeFileSync(
  path.join(dist, "index.mjs"),
  `export * from "./esm/index.js";\n`,
  "utf8",
);

fs.writeFileSync(
  path.join(dist, "index.cjs"),
  `module.exports = require("./esm/index.js");\n`,
  "utf8",
);

// Clean up types directory
fs.rmSync(path.join(dist, "types"), { recursive: true, force: true });

console.log("Build complete");
